-- ============================================================
-- Discord Mod Tracker —— Supabase 数据库初始化脚本
-- 用法：打开 Supabase 控制台 → 左侧 SQL Editor → 新建查询 → 粘贴本文件全部内容 → Run
-- 可以重复执行，不会报错、不会丢数据
-- ============================================================

-- ------------------------------------------------------------
-- 1. 消息表：保存被监控频道里的每一条消息
-- ------------------------------------------------------------
create table if not exists public.messages (
  id                  bigint generated by default as identity primary key,
  discord_message_id  text        not null unique,   -- Discord 消息 ID，用于去重
  channel_id          text        not null,
  channel_name        text,
  guild_id            text,
  author_id           text        not null,
  author_name         text        not null,          -- 用户名（唯一）
  author_display_name text,                          -- 服务器昵称（可能重复，仅供参考）
  content             text        not null default '',
  attachments         jsonb       not null default '[]'::jsonb,  -- 附件列表
  reply_to_id         text,                          -- 若为回复，记录被回复的消息 ID
  created_at          timestamptz not null,          -- 消息在 Discord 的发送时间
  inserted_at         timestamptz not null default now()
);

-- 加速"按频道 + 时间范围查询"，这是 /check 的核心查询
create index if not exists messages_channel_created_idx
  on public.messages (channel_id, created_at desc);

create index if not exists messages_author_idx
  on public.messages (author_id);

-- ------------------------------------------------------------
-- 2. check 记录表：记录每次 /check 的时间点与总结内容
--    下一次 /check 会从这张表里最后一条记录的 period_end 开始算
-- ------------------------------------------------------------
create table if not exists public.check_records (
  id                bigint generated by default as identity primary key,
  channel_id        text        not null,
  period_start      timestamptz,                     -- 本次总结的起始时间
  period_end        timestamptz not null default now(), -- 本次总结的结束时间（下次的起点）
  message_count     integer     not null default 0,
  summary           text,                            -- AI 生成的总结全文，便于回溯
  requested_by_id   text,
  requested_by_name text,
  created_at        timestamptz not null default now()
);

create index if not exists check_records_channel_idx
  on public.check_records (channel_id, period_end desc);

-- ------------------------------------------------------------
-- 3. 安全设置：开启行级安全（RLS）
--    Bot 使用 service_role 密钥，会绕过 RLS，功能不受影响；
--    但这样可防止有人拿到匿名密钥后读取你的聊天记录
-- ------------------------------------------------------------
alter table public.messages      enable row level security;
alter table public.check_records enable row level security;

-- ------------------------------------------------------------
-- 完成！可以在左侧 Table Editor 看到 messages 和 check_records 两张表
-- ------------------------------------------------------------
